# Pterodactyl optimized settings
server-port={{SERVER_PORT}}
server-ip={{SERVER_IP}}
view-distance=6
simulation-distance=4
max-tick-time=60000
use-native-transport=true
sync-chunk-writes=false
enable-query=true
query.port={{SERVER_PORT}}
enable-rcon=true
rcon.port={{RCON_PORT}}
rcon.password={{RCON_PASSWORD}}